### PR TITLE
trying to solve the map3d error

### PR DESCRIPTION
**Pull request by telemaxx**
i send directly to master, or should we use a new branch?

i can not test it, because in eclipse it is running always ;-)
https://sourceforge.net/p/mytourbook/discussion/622811/thread/499a95f703/

### CODE REVIEW

**Comment by FJBDev** [comment]
@telemaxx Can you create a build from this branch, I'd be happy to test it

**Comment by telemaxx** [comment]
no,  seems so that only Wolfgang can build it. i tough you could also ;-)

**Comment by FJBDev** [comment]
> 
> 
> no, seems so that only Wolfgang can build it. i tough you could also ;-)

Sure, I can do a build :-) ( i thought you had done it). I will work on that either today or tomorrow and will let you know if I see the 3d issue resolved

**Comment by FJBDev** [comment]
I just started the build :-)

**Comment by FJBDev** [comment]
Dang, the build already failed :-(

:create-build-files
---------------------------------------------------------------------------------------

[ant:echo] Delete old build files: ../../../../mytourbook-BUILD-autocreated
[ant:echo] Copy core files into ../../../../mytourbook-BUILD-autocreated/core
[ant:echo] Copy language fragments into ../../../../mytourbook-BUILD-autocreated/translation
[ant:echo] Copy language property files into ../../../../mytourbook-BUILD-autocreated/translation


:mt_10_CreateBuildFiles
---------------------------------------------------------------------------------------



:mt_20_BuildProduct
---------------------------------------------------------------------------------------

[INFO] Scanning for projects...
C:\Users\frederic\git\mytourbook-BUILD-autocreated\core\net.tourbook\.polyglot.build.properties
C:\Users\frederic\git\mytourbook-BUILD-autocreated\core\net.tourbook.branding\.polyglot.build.properties
C:\Users\frederic\git\mytourbook-BUILD-autocreated\core\net.tourbook.chart\.polyglot.build.properties
C:\Users\frederic\git\mytourbook-BUILD-autocreated\core\net.tourbook.common\.polyglot.build.properties
C:\Users\frederic\git\mytourbook-BUILD-autocreated\core\net.tourbook.device\.polyglot.build.properties
C:\Users\frederic\git\mytourbook-BUILD-autocreated\core\net.tourbook.device.garmin\.polyglot.build.properties
C:\Users\frederic\git\mytourbook-BUILD-autocreated\core\net.tourbook.device.garmin.fit\.polyglot.build.properties
C:\Users\frederic\git\mytourbook-BUILD-autocreated\core\net.tourbook.device.nmea\.polyglot.build.properties
C:\Users\frederic\git\mytourbook-BUILD-autocreated\core\net.tourbook.export\.polyglot.build.properties
C:\Users\frederic\git\mytourbook-BUILD-autocreated\core\net.tourbook.p2\.polyglot.build.properties
C:\Users\frederic\git\mytourbook-BUILD-autocreated\core\net.tourbook.photo\.polyglot.build.properties
C:\Users\frederic\git\mytourbook-BUILD-autocreated\core\net.tourbook.printing\.polyglot.build.properties
C:\Users\frederic\git\mytourbook-BUILD-autocreated\core\net.tourbook.statistics\.polyglot.build.properties
C:\Users\frederic\git\mytourbook-BUILD-autocreated\core\net.tourbook.web\.polyglot.build.properties
C:\Users\frederic\git\mytourbook-BUILD-autocreated\core\net.tourbook.ext.apache\.polyglot.build.properties
C:\Users\frederic\git\mytourbook-BUILD-autocreated\core\net.tourbook.ext.ejb3_3.4.0\.polyglot.build.properties
C:\Users\frederic\git\mytourbook-BUILD-autocreated\core\net.tourbook.ext.geoclipse\.polyglot.build.properties
C:\Users\frederic\git\mytourbook-BUILD-autocreated\core\net.tourbook.ext.jars\.polyglot.build.properties
C:\Users\frederic\git\mytourbook-BUILD-autocreated\core\net.tourbook.ext.jars.printing\.polyglot.build.properties
C:\Users\frederic\git\mytourbook-BUILD-autocreated\core\net.tourbook.ext.rxtx.linux64_2.2\.polyglot.build.properties
C:\Users\frederic\git\mytourbook-BUILD-autocreated\core\net.tourbook.ext.rxtx.macosx_2.2\.polyglot.build.properties
C:\Users\frederic\git\mytourbook-BUILD-autocreated\core\net.tourbook.ext.rxtx.win64_2.2\.polyglot.build.properties
C:\Users\frederic\git\mytourbook-BUILD-autocreated\core\net.tourbook.ext.rxtx_2.2\.polyglot.build.properties
C:\Users\frederic\git\mytourbook-BUILD-autocreated\core\net.tourbook.ext.velocity\.polyglot.build.properties
C:\Users\frederic\git\mytourbook-BUILD-autocreated\core\net.tourbook.ext.vtm\.polyglot.build.properties
C:\Users\frederic\git\mytourbook-BUILD-autocreated\core\net.tourbook.ext.vtm.linux\.polyglot.build.properties
C:\Users\frederic\git\mytourbook-BUILD-autocreated\core\net.tourbook.ext.vtm.macosx\.polyglot.build.properties
C:\Users\frederic\git\mytourbook-BUILD-autocreated\core\net.tourbook.ext.vtm.windows\.polyglot.build.properties
C:\Users\frederic\git\mytourbook-BUILD-autocreated\core\net.tourbook.ext.worldwind.linux64_2.0\.polyglot.build.properties
C:\Users\frederic\git\mytourbook-BUILD-autocreated\core\net.tourbook.ext.worldwind.macosx_2.0\.polyglot.build.properties
C:\Users\frederic\git\mytourbook-BUILD-autocreated\core\net.tourbook.ext.worldwind.win64_2.0\.polyglot.build.properties
C:\Users\frederic\git\mytourbook-BUILD-autocreated\core\net.tourbook.ext.worldwind_2.0\.polyglot.build.properties
C:\Users\frederic\git\mytourbook-BUILD-autocreated\translation\net.tourbook.chart.nl\.polyglot.build.properties
C:\Users\frederic\git\mytourbook-BUILD-autocreated\translation\net.tourbook.common.nl\.polyglot.build.properties
C:\Users\frederic\git\mytourbook-BUILD-autocreated\translation\net.tourbook.device.garmin.fit.nl\.polyglot.build.properties
C:\Users\frederic\git\mytourbook-BUILD-autocreated\translation\net.tourbook.device.garmin.nl\.polyglot.build.properties
C:\Users\frederic\git\mytourbook-BUILD-autocreated\translation\net.tourbook.device.nl\.polyglot.build.properties
C:\Users\frederic\git\mytourbook-BUILD-autocreated\translation\net.tourbook.device.nmea.nl\.polyglot.build.properties
C:\Users\frederic\git\mytourbook-BUILD-autocreated\translation\net.tourbook.nl\.polyglot.build.properties
C:\Users\frederic\git\mytourbook-BUILD-autocreated\translation\net.tourbook.photo.nl\.polyglot.build.properties
C:\Users\frederic\git\mytourbook-BUILD-autocreated\translation\net.tourbook.printing.nl\.polyglot.build.properties
C:\Users\frederic\git\mytourbook-BUILD-autocreated\translation\net.tourbook.statistics.nl\.polyglot.build.properties
C:\Users\frederic\git\mytourbook-BUILD-autocreated\translation\net.tourbook.web.nl\.polyglot.build.properties
C:\Users\frederic\git\MT\mytourbook\features\feature.net.tourbook.app\.polyglot.build.properties
C:\Users\frederic\git\MT\mytourbook\features\feature.net.tourbook.app.nl\.polyglot.build.properties
C:\Users\frederic\git\MT\mytourbook\features\feature.net.tourbook.app.version\.polyglot.build.properties
C:\Users\frederic\git\MT\mytourbook\features\feature.net.tourbook.ext.derby\.polyglot.build.properties
C:\Users\frederic\git\MT\mytourbook\features\feature.net.tourbook.ext.eclipse\.polyglot.build.properties
C:\Users\frederic\git\MT\mytourbook\features\feature.net.tourbook.ext.eclipse.nl\.polyglot.build.properties
C:\Users\frederic\git\MT\mytourbook\features\feature.net.tourbook.ext.ejb3\.polyglot.build.properties
C:\Users\frederic\git\MT\mytourbook\features\feature.net.tourbook.ext.jars\.polyglot.build.properties
C:\Users\frederic\git\MT\mytourbook\features\feature.net.tourbook.ext.rxtx\.polyglot.build.properties
C:\Users\frederic\git\MT\mytourbook\features\feature.net.tourbook.ext.vtm\.polyglot.build.properties
C:\Users\frederic\git\MT\mytourbook\features\feature.net.tourbook.ext.worldwind_2.0\.polyglot.build.properties
C:\Users\frederic\git\MT\mytourbook\build\build.net.tourbook.feature\.polyglot.build.properties
[INFO] Computing target platform for MavenProject: net.tourbook:net.tourbook:20.2.0-SNAPSHOT @ C:\Users\frederic\git\mytourbook-BUILD-autocreated\core\net.tourbook\.polyglot.build.properties
[INFO] Fetching p2.index from https://download.eclipse.org/releases/2019-12/
[INFO] Fetching p2.index from https://download.eclipse.org/releases/2019-12/
[INFO] Adding repository https://download.eclipse.org/releases/2019-12
[INFO] Fetching p2.index from https://download.eclipse.org/technology/epp/packages/2019-12/
[INFO] Fetching p2.index from https://download.eclipse.org/technology/epp/packages/2019-12/
[INFO] Fetching p2.index from https://download.eclipse.org/releases/2019-12/201912181000/
[INFO] Fetching p2.index from https://download.eclipse.org/releases/2019-12/201912181000/
[INFO] Adding repository file:build/build.eclipse.4.14.nl.repo
[ERROR] Internal error: java.lang.RuntimeException: Failed to load p2 repository with ID 'eclipse.4.14.nl' from location file:build/build.eclipse.4.14.nl.repo: URI is not hierarchical -> [Help 1]
org.apache.maven.InternalErrorException: Internal error: java.lang.RuntimeException: Failed to load p2 repository with ID 'eclipse.4.14.nl' from location file:build/build.eclipse.4.14.nl.repo
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:120)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:956)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:290)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:194)
    at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:498)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:289)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:229)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:415)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:356)
Caused by: java.lang.RuntimeException: Failed to load p2 repository with ID 'eclipse.4.14.nl' from location file:build/build.eclipse.4.14.nl.repo
    at org.eclipse.tycho.p2.target.TargetPlatformFactoryImpl.loadMetadataRepository (TargetPlatformFactoryImpl.java:302)
    at org.eclipse.tycho.p2.target.TargetPlatformFactoryImpl.gatherExternalInstallableUnits (TargetPlatformFactoryImpl.java:270)
    at org.eclipse.tycho.p2.target.TargetPlatformFactoryImpl.createTargetPlatform (TargetPlatformFactoryImpl.java:176)
    at org.eclipse.tycho.p2.target.TargetPlatformFactoryImpl.createTargetPlatform (TargetPlatformFactoryImpl.java:128)
    at org.eclipse.tycho.p2.target.TargetPlatformFactoryImpl.createTargetPlatform (TargetPlatformFactoryImpl.java:1)
    at org.eclipse.tycho.p2.manager.ReactorRepositoryManagerImpl.computePreliminaryTargetPlatform (ReactorRepositoryManagerImpl.java:84)
    at org.eclipse.tycho.p2.resolver.P2DependencyResolver.computePreliminaryTargetPlatform (P2DependencyResolver.java:224)
    at org.eclipse.tycho.core.resolver.DefaultTychoResolver.resolveProject (DefaultTychoResolver.java:110)
    at org.eclipse.tycho.core.maven.TychoMavenLifecycleParticipant.afterProjectsRead (TychoMavenLifecycleParticipant.java:95)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:264)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:956)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:290)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:194)
    at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:498)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:289)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:229)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:415)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:356)
Caused by: org.eclipse.equinox.p2.core.ProvisionException: URI is not hierarchical
    at org.eclipse.equinox.internal.p2.engine.ProfileMetadataRepository.<init> (ProfileMetadataRepository.java:53)
    at org.eclipse.equinox.internal.p2.engine.ProfileMetadataRepositoryFactory.load (ProfileMetadataRepositoryFactory.java:41)
    at org.eclipse.equinox.internal.p2.metadata.repository.MetadataRepositoryManager.factoryLoad (MetadataRepositoryManager.java:63)
    at org.eclipse.equinox.internal.p2.repository.helpers.AbstractRepositoryManager.loadRepository (AbstractRepositoryManager.java:770)
    at org.eclipse.equinox.internal.p2.repository.helpers.AbstractRepositoryManager.loadRepository (AbstractRepositoryManager.java:671)
    at org.eclipse.equinox.internal.p2.metadata.repository.MetadataRepositoryManager.loadRepository (MetadataRepositoryManager.java:110)
    at org.eclipse.tycho.p2.remote.RemoteMetadataRepositoryManager.loadRepository (RemoteMetadataRepositoryManager.java:61)
    at org.eclipse.tycho.p2.remote.RemoteMetadataRepositoryManager.loadRepository (RemoteMetadataRepositoryManager.java:53)
    at org.eclipse.tycho.p2.target.TargetPlatformFactoryImpl.loadMetadataRepository (TargetPlatformFactoryImpl.java:298)
    at org.eclipse.tycho.p2.target.TargetPlatformFactoryImpl.gatherExternalInstallableUnits (TargetPlatformFactoryImpl.java:270)
    at org.eclipse.tycho.p2.target.TargetPlatformFactoryImpl.createTargetPlatform (TargetPlatformFactoryImpl.java:176)
    at org.eclipse.tycho.p2.target.TargetPlatformFactoryImpl.createTargetPlatform (TargetPlatformFactoryImpl.java:128)
    at org.eclipse.tycho.p2.target.TargetPlatformFactoryImpl.createTargetPlatform (TargetPlatformFactoryImpl.java:1)
    at org.eclipse.tycho.p2.manager.ReactorRepositoryManagerImpl.computePreliminaryTargetPlatform (ReactorRepositoryManagerImpl.java:84)
    at org.eclipse.tycho.p2.resolver.P2DependencyResolver.computePreliminaryTargetPlatform (P2DependencyResolver.java:224)
    at org.eclipse.tycho.core.resolver.DefaultTychoResolver.resolveProject (DefaultTychoResolver.java:110)
    at org.eclipse.tycho.core.maven.TychoMavenLifecycleParticipant.afterProjectsRead (TychoMavenLifecycleParticipant.java:95)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:264)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:956)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:290)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:194)
    at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:498)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:289)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:229)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:415)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:356)
Caused by: java.lang.IllegalArgumentException: URI is not hierarchical
    at java.io.File.<init> (File.java:418)
    at org.eclipse.equinox.internal.p2.engine.ProfileMetadataRepository.getProfile (ProfileMetadataRepository.java:179)
    at org.eclipse.equinox.internal.p2.engine.ProfileMetadataRepository.<init> (ProfileMetadataRepository.java:51)
    at org.eclipse.equinox.internal.p2.engine.ProfileMetadataRepositoryFactory.load (ProfileMetadataRepositoryFactory.java:41)
    at org.eclipse.equinox.internal.p2.metadata.repository.MetadataRepositoryManager.factoryLoad (MetadataRepositoryManager.java:63)
    at org.eclipse.equinox.internal.p2.repository.helpers.AbstractRepositoryManager.loadRepository (AbstractRepositoryManager.java:770)
    at org.eclipse.equinox.internal.p2.repository.helpers.AbstractRepositoryManager.loadRepository (AbstractRepositoryManager.java:671)
    at org.eclipse.equinox.internal.p2.metadata.repository.MetadataRepositoryManager.loadRepository (MetadataRepositoryManager.java:110)
    at org.eclipse.tycho.p2.remote.RemoteMetadataRepositoryManager.loadRepository (RemoteMetadataRepositoryManager.java:61)
    at org.eclipse.tycho.p2.remote.RemoteMetadataRepositoryManager.loadRepository (RemoteMetadataRepositoryManager.java:53)
    at org.eclipse.tycho.p2.target.TargetPlatformFactoryImpl.loadMetadataRepository (TargetPlatformFactoryImpl.java:298)
    at org.eclipse.tycho.p2.target.TargetPlatformFactoryImpl.gatherExternalInstallableUnits (TargetPlatformFactoryImpl.java:270)
    at org.eclipse.tycho.p2.target.TargetPlatformFactoryImpl.createTargetPlatform (TargetPlatformFactoryImpl.java:176)
    at org.eclipse.tycho.p2.target.TargetPlatformFactoryImpl.createTargetPlatform (TargetPlatformFactoryImpl.java:128)
    at org.eclipse.tycho.p2.target.TargetPlatformFactoryImpl.createTargetPlatform (TargetPlatformFactoryImpl.java:1)
    at org.eclipse.tycho.p2.manager.ReactorRepositoryManagerImpl.computePreliminaryTargetPlatform (ReactorRepositoryManagerImpl.java:84)
    at org.eclipse.tycho.p2.resolver.P2DependencyResolver.computePreliminaryTargetPlatform (P2DependencyResolver.java:224)
    at org.eclipse.tycho.core.resolver.DefaultTychoResolver.resolveProject (DefaultTychoResolver.java:110)
    at org.eclipse.tycho.core.maven.TychoMavenLifecycleParticipant.afterProjectsRead (TychoMavenLifecycleParticipant.java:95)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:264)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:956)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:290)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:194)
    at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:498)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:289)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:229)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:415)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:356)
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/InternalErrorException
:mt_20_BuildProduct FAILED


2 actionable tasks: 2 executed

**Comment by FJBDev** [comment]
Maybe I didn't fully update the p2 repo as prescribed [here](https://github.com/wolfgang-ch/mytourbook/blob/master/build/build.eclipse.4.14.nl.repo/How%20to%20update%20this%20p2%20repo.txt), I will work on that

**Comment by FJBDev** [comment]
Ok, that was it, i started the build again and it seems better now

**Comment by FJBDev** [comment]
[Here](https://www.dropbox.com/s/hm7o2b0eyc9j4w9/mytourbook-20.2.0-win-64-setup-telemaxxfix.exe?dl=0) is the MT build I created and uploaded so you can try it

**Comment by FJBDev** [comment]
And I just installed the build with your fix and it works for me, good job 👍 @telemaxx 

image

**Comment by telemaxx** [comment]
grafik
nice build

**Comment by wolfgang-ch** [comment]
When I tested the 3D map then I discovered this issue https://github.com/wolfgang-ch/mytourbook/commit/7ff33042a3a0558e393b38743471a12b2cb4c45d which occures when you doubleclick a 3d map color profile

**Comment by FJBDev** [comment]
> 
> 
> When I tested the 3D map then I discovered this issue [7ff3304](https://github.com/wolfgang-ch/mytourbook/commit/7ff33042a3a0558e393b38743471a12b2cb4c45d) which occures when you doubleclick a 3d map color profile

I saw the same thing too but i didn't check if it was already an issue in 19.10 as I dont use 3d map

**Comment by FJBDev** [comment]
One thing I don't understand is that, to my knowledge, no changes were made in the 3D map code between 19.10 and 20.2... is it possible the changes were made in the eclipse SWT that would cause this issue ?

**Comment by telemaxx** [comment]
i am not sure anymore, that it was fixed due my little code change.
Maybe it was fixed due the fact that @FJBDev was using Java8 for developing/building and @wolfgang-ch was using java 13.
We should do a test, when @wolfgang-ch did build the project with his new java13 setup.

**Comment by FJBDev** [comment]
I don't think it should matter which Java version @wolfgang-ch  used as MT is configured to build with 8 ? But I could be wrong

As for your fix, I would think it's valid since I didn't change anything on my laptop test except the MT version that has your fix.

But you're right, let's double check and be sure

**Comment by wolfgang-ch** [comment]
I can confirm, that Java 8 (Win10) causes this error for the official MT 20.2

`SEVERE: Exception encountered while repainting
java.lang.NoSuchMethodError: java.nio.FloatBuffer.clear()Ljava/nio/FloatBuffer;
        at net.tourbook.map3.layer.tourtrack.TrackPathOptimized.computeArrowPositions(TrackPathOptimized.java:203)
        at net.tourbook.map3.layer.tourtrack.TrackPathOptimized.computeAbsolutePoints(TrackPathOptimized.java:84)
        at gov.nasa.worldwind.render.Path.computePath(Unknown Source)
        at gov.nasa.worldwind.render.Path.doMakeOrderedRenderable(Unknown Source)`

**Comment by wolfgang-ch** [comment]
I also can confirm now that this fix has fixed the 3d map issue

**Comment by wolfgang-ch** [comment]
> 
> 
> One thing I don't understand is that, to my knowledge, no changes were made in the 3D map code between 19.10 and 20.2... is it possible the changes were made in the eclipse SWT that would cause this issue ?

I think changes in the SWT caused the error, the same code is used also in `DialogSelectSRTMColors` and there, the unmodified code is still running it has just another UI layout

**Pull request merged**
