### PR TITLE
Feature - 170

### PR DESCRIPTION
**Pull request by rtdog**
This includes feature 170 (spm/rpm).

The formatting is broken in a few of the files.  I can work to fix that I, I think I figured out how to get the sorting working.

### CODE REVIEW

**Comment by wolfgang-ch** [comment]
> The formatting is broken in a few of the files. I can work to fix that I, I think I figured out how to get the sorting working.

You have not yet fully setup the IDE http://mytourbook.sourceforge.net/mytourbook/index.php/development/dev-ide/code-style your `Members Sort Order` is wrong.

I just created "your" branch `contributor-rtdog` because this PR is against `main`.

I'm not sure if I should merge this PR into 20.8 because I wanted to publish it tomorrow and this is not yet tested.

**Comment by wolfgang-ch** [comment]
170 link https://sourceforge.net/p/mytourbook/feature-requests/170/

**Comment by rtdog** [comment]
@wolfgang-ch , please let me know how to use the contributor-rtdog branch.  Are you expecting that I issue pull requests into this branch so changes can be tested there prior to main?  Or do I have permissions on that branch so I can do the work there directly?

**Comment by wolfgang-ch** [comment]
@rtdog , you can use any of your private branches to do your development. Before you create a PR, merge your development branch into `contributor-rtdog` and then merge `main` into "your" `contributor-rtdog` and use this for the PR. You can merge `main` at any time into your development branch which I also recommend then you have less conflicts at the end but it depends what you are developing.

You could also do your development in `contributor-rtdog` but never create the PR for the `main` branch.

The `main` should be the the most stable branch.

**Comment by rtdog** [comment]
ok, I'll work it up over there and submit another one.  Thanks!

**Pull request closed without merging**
