### PR TITLE
Map25:  reducing "noise" due comments. adding map25 option "show photo title"

### PR DESCRIPTION
**Pull request by telemaxx**
changed multi line comments and changed map25provider slideout

/** */ into /* */

grafik

### CODE REVIEW

**Comment by FJBDev** [comment]
@telemaxx 

Your Map2.5D work reminded me that I have always had an issue with this Map Provider slideout in Linux (My Linux is [Debian 10.4](https://www.debian.org/News/2020/20200509)).

[Here](https://www.dropbox.com/s/47xydwwx6nlwe48/Map2.5%20Map%20Provide%20slideout%20Issue.mp4?dl=0) is a video that shows my problem :
- Open the 2.5D view
- Clicking on either the **Map Provider** or **Theme** dropdown menus make them disappear.

I have made this video using your latest branch [map25-experimental](https://github.com/telemaxx/mytourbook/tree/map25-experimental)

**Comment by telemaxx** [comment]
@FJBDev:
The slideout was written by @wolfgang-ch 

A while ago i had tried to write a slideout for the new 2.5d photolayer.
For that, i copied some code from existing slideouts, but my slideout was never doing what i want. so i giving up and use a simple on/off switch in the menu.
for that crazy stuff my swt skills not enougth. ;-(

Maybe @wolfgang-ch can crosscheck, i have also no linux desktop.

Have you tried, what happen, if configure a second map provider via the mt settings?

But good to see that the new provider "mapilion" is working.

**Comment by FJBDev** [comment]
>Have you tried, what happen, if configure a second map provider via the mt settings?

I tried and while it seems to work a little better, I now also see issued where the slideout freezes.

**Comment by wolfgang-ch** [comment]
Should this PR be merged into MT 20.8, when 638 files have been changed, then it is difficult to predict it.

pr-files

**Comment by telemaxx** [comment]
the last days i merged main to map25-experimental.
that are lot of changes. dropbox, flat tourbook view. i think this are the most of the 638 files changed.
should i reverd this merge? i have only changed 1-2 dozents of files. mostly changing the formatting(comments)

**Pull request closed without merging**
