### PR TITLE
20.2 : Changes per code review

### PR DESCRIPTION
**Pull request by FJBDev**
1. Reverted the reformatted comments and sorting of the code. 
/net.tourbook/src/net/tourbook/map25/layer/marker/MarkerToolkit.java
/net.tourbook/src/net/tourbook/map25/Map25App.java
/net.tourbook/src/net/tourbook/preferences/MapsforgeStyleParser.java
<br /><br /><br />

2. Reverted the "external" files \\

/net.tourbook/src/net/tourbook/math/Fmath.java
/net.tourbook/src/net/tourbook/proxy/DefaultProxySelector.java

com.skedgo.converter.TimezoneMapper
==> I kept that one as I have updated it to the latest version found [here](https://github.com/drtimcooper/LatLongToTimezone/blob/master/src/main/java/com/skedgo/converter/TimezoneMapper.java)
<br /><br /><br />

3. Fixed Inconsistent naming
CreateUI_110_AltitudeRadioButtons()
CreateUI_120_PulseRadioButtons()
CreateUI_130_CadenceRadioButtons()
CreateUI_140_TemperatureRadioButtons()
<br /><br /><br />

4. Edit Time Slices dialog

- Rearranged the dialog per code review
- Using the formtoolkit for the checkbox fields to use the correct background color
- Added Mnemonics

image

<br /><br /><br />

5. Added a mnemonic ("v" to open the time slices editor dialog)
image
<br /><br /><br />

6.  Reverted wrong formatting

- TourDataEditorView
- net.tourbook.photo.Photo

<br /><br /><br />

7. _TourDataEditorView_: Fixed Inconsistent naming: _tsComparator -> _timeSlice_Comparator
<br /><br /><br />

8. _TourDataEditorView_: Put the calculation of the boolean values in the upper part of the method, to better see the controls

New work : 
* Fixed a bug in the calendar view where the speed was always displayed in metric

### CODE REVIEW

**Comment by wolfgang-ch** [comment]
I merged your commits into master but have these smaller issues

1. I'm not very happy with the new text keys for the new timeslices dialog

Dialog_Edit_Checkbox_NewValues           = New values
Dialog_Edit_Checkbox_OffsetValues        = Offset values
Dialog_Edit_Label_Altitude               = &Altitude
Dialog_Edit_Label_Altitude_Tooltip       = The value entered will replace or offset the existing altitude values
Dialog_Edit_Label_Cadence                = &Cadence
Dialog_Edit_Label_Cadence_Tooltip        = The value entered will replace or offset the existing cadence values
Dialog_Edit_Label_Pulse                  = Puls&e
Dialog_Edit_Label_Pulse_Tooltip          = The value entered will replace or offset the existing pulse values
Dialog_Edit_Label_Temperature            = &Temperature
Dialog_Edit_Label_Temperature_Tooltip    = The value entered will replace or offset the existing temperature values
Dialog_Edit_Timeslices_Values_Area_Title = Replace or offset the time slice values
Dialog_Edit_Timeslices_Values_Title      = Edit all time slices values


Dialog_Edit_... is too common for the prefix as the first and the second _ component do categorize the text keys


A better prefix would be

Dialog_EditTimeslicesValues_...

or

Dialog_EditTimeslices_...



2. These text keys are now checkboxes and not labels

Dialog_Edit_Label_Altitude               
Dialog_Edit_Label_Cadence                
Dialog_Edit_Label_Pulse                  
Dialog_Edit_Label_Temperature

**Comment by wolfgang-ch** [comment]
>These text keys are now checkboxes and not labels
I do critizise this issue, because it gives the translators a hint for which control it is used for

**Comment by FJBDev** [comment]
I will fix those issues soon

**Comment by wolfgang-ch** [comment]
When in the new edit time slices dialog an item (altitude, cadence,...) is not selected (checked) then the correspondig fields should be disabled.

A comfort feature maybe be to keep the state of the selected items/field values when the dialog is closed/reopened as this done also in other dialogs.

**Pull request merged**
