### PR TITLE
Added: FIT File Import: Option to set TourType to SportName from file

### PR DESCRIPTION
**Pull request by bbbbbr**
Hello,

Not sure if there is a standard process for a pull request on this project- so let me know if any changes need to be made to meet code standards and pull request information, or if there would be a more appropriate way to implement this feature.

I've added a feature to set the Tour Type based on the "Sport Name" when importing from Garmin FIT Files (useful to me, perhaps for others too). There is a preferences panel checkbox to control the behavior (it is turned off by default).

It is related to this feature request I opened:
https://sourceforge.net/p/mytourbook/feature-requests/158/

Thanks!

### CODE REVIEW

**Comment by FJBDev** [comment]
@bbbbbr 
For the code standards, see the doc [here](http://mytourbook.sourceforge.net/mytourbook/index.php/development/dev-ide/code-style)

Is this PR related to this [feature request](https://sourceforge.net/p/mytourbook/feature-requests/158/) ?

**Comment by bbbbbr** [comment]
@FJBDev

> For the code standards, and to configure eclipse with Wolfgang's code style, see the doc  here

Thanks. When I import and enable those settings in Eclipse and then save, it results in extensive white-space changes in the saved files. Is that intended and desired? (Maybe I made a mistake in the configuration. I will try again.) 

In this case I've tried to tread lightly in the modified files.

> Is this PR related to this feature request ? ( https://sourceforge.net/p/mytourbook/feature-requests/158/ )

Yes, I opened that request a while ago

**Comment by FJBDev** [comment]
> 
>When I import and enable those settings in Eclipse and then save, it results in extensive white-space changes in the saved files. Is that intended and desired? (Maybe I made a mistake in the configuration. I will try again.)
> 
> In this case I've tried to tread lightly in the modified files.

==> It is possible if for example the file hasn't been touched in months/years as the eclipse formatter and clean up settings are changed sometimes by Wolfgang.

> 
> > Is this PR related to this feature request ? ( https://sourceforge.net/p/mytourbook/feature-requests/158/ )
> 
> Yes, I opened that request a while ago

==> Superb, maybe just mention that in your first comment with the link to the feature request for reference.

**Comment by bbbbbr** [comment]
Thanks for the guidance, I've updated the first comment.

**Comment by wolfgang-ch** [comment]
@bbbbbr Can you create this PR into the new branch https://github.com/wolfgang-ch/mytourbook/tree/Common_PullRequests_Branch because the master should contain only validated code and I validate the code with the Eclipse IDE and not with this awful github compare featue

**Comment by telemaxx** [comment]
> I've added a feature to set the Tour Type based on the "Sport Name" when importing from Garmin FIT Files (useful to me, perhaps for others too). There is a preferences panel checkbox to control the behavior (it is turned off by default).
> 
> It is related to this feature request I opened:
> https://sourceforge.net/p/mytourbook/feature-requests/158/
> 

Great Idea, i also had thought in that direction.

At the moment imported fit-files have no title in mt.
so my idea was to create a title like:
date-sportname-device
eg 2020-02-24_biking_fenix

setting a tourtype is of course also cool.
is there a mapping like
Cyclocross -> my_own_typename?

I am very excited to try it out!

**Comment by bbbbbr** [comment]
@wolfgang-ch
I've changed the merge target to Common_PullRequests_Branch

@telemaxx 
To keep the implementation simplified there is no mapping. It uses the sport name literally (ex: "CYCLING"). If there is no existing entry that matches then it will create a new Tour Type. 

I did consider appending the sub_sport_name field as well, but that might be more appropriate as a Tag perhaps. I am still acclimating to the software and how it's organized.

Auto setting of Title could be a nice feature.

**Comment by FJBDev** [comment]
@bbbbbr 
Also, please update the [readme file](https://github.com/wolfgang-ch/mytourbook/blob/master/info/release-notes/20.month.0-readme.txt) so it contains the description of your changes/fixes/new features for the next release.

**Comment by bbbbbr** [comment]
@FJBDev 

Thanks, added the note

**Comment by wolfgang-ch** [comment]
When you activate the logging for the .fit file import you can see all available data contained in the fit file.

You can selectively enable/disable (comment/uncomment) what is logged because there is a lot of data.

In this screenshot, only the profile name of a tour is is activated

fit-logging


On the left side of the next screenshot you can see the import with your PR. Because the Sportname is a static field within the FIT SDK, it do not recognize the used profile in the garmin device. 

On the right side you can see the used profile name when a tour was recorded. (It's a mix of german english and swiss language :-)

fit-import-profile-vs-sport-name

I think your feature would be helpful when the profile name could be used as tour type. Maybe the user could choose if it is using the Sport Name or the Profile Name to set the Tour Type

**Comment by wolfgang-ch** [comment]
@bbbbbr I forgot to mention you in the previous comment

**Comment by bbbbbr** [comment]
@wolfgang-ch Yes, it could be a good option. 

I've turned fit logging on and now see the Profile Name in the logs, though it is not always populated, whereas Sport Name is always present. It would be good to handle that condition into the option.

A couple possible approaches:

* Select one or the other. If Profile Name is selected and not present then it will just not get set and that is OK
* When Profile Name is not present fall back to using Sport Name
* Single enable, and when enabled, Concatenate them such as : Sport Name || '-' || Profile Name
* Separate enables for each field, if both enabled then they are both concatenated such as above

At first glance I don't see an accessor such as getName() in the session message listener.  I'll dig around some (perhaps in workout message). If you know off-hand of a way to read it please let me know.

**Comment by wolfgang-ch** [comment]
@bbbbbr 

There is enough realestate in the fit pref page, so all of your options could be provided to the user, they just needs to be implemented :-)

I would implement it with radio buttons (instead of a drop down box) which has the advantage that you can see all options at once.

**Comment by bbbbbr** [comment]
@wolfgang-ch 

Giving it a try

**Comment by wolfgang-ch** [comment]
@bbbbbr You have to create a new pull request for your changes because a merge can be done only once for each PR :-(

**Comment by bbbbbr** [comment]
@wolfgang-ch Yeah, will do. Likely later in the week.

**Pull request merged**
