### PR TITLE
Map25: direction arrows on the track

### PR DESCRIPTION
**Pull request by telemaxx**
https://sourceforge.net/p/mytourbook/feature-requests/195/

grafik

### CODE REVIEW

**Comment by FJBDev** [comment]
Looks like those labels should be vertically aligned
image

**Comment by telemaxx** [comment]
Some slideouts need some rework... when you click the color chooser,  the window opened behind the slideout. @wolfgang-ch solved that behaviour in other slideouts.

**Comment by telemaxx** [comment]
@FJBDev i have shorten the text a bit.
it looks better now but not perfect. not sure how to handle this swt thinks...
grafik

**Comment by wolfgang-ch** [comment]
When I open the color picker dialog also in other slideouts, this dialog is pinned in the center of the MT main window with Ubuntu 20.04, however it can be behind the slideout but it can be move to be fully accessible.

**Comment by wolfgang-ch** [comment]
I did some UI adjustments :-)

image

**Comment by telemaxx** [comment]
thank you,  that's looks good. 
and now the translators can use longer words,  without destroying the layout. 

high tec developer@work:

**Comment by wolfgang-ch** [comment]
I use the same tools (paper and pen) when something gets complicated :-)

and I cannot remember when is Latitude and Longitude, this is my "Eselsbrücke":
It is "Lon" when it starts in "London" which has longitude = 0

**Comment by telemaxx** [comment]
I like this Eselsbrücke :-)

**Pull request merged**
