### PR TITLE
[StatisticTooltip] Bugfix where the elevation value is already converted in the appropriate unit

### PR DESCRIPTION
**Pull request by FJBDev**
@wolfgang-ch Do you know those too ? I just discovered and played with them :smile: 

[mouseEnterAdapter](http://help.eclipse.org/2021-03/topic/org.eclipse.platform.doc.isv/reference/api/org/eclipse/swt/events/MouseTrackListener.html#mouseEnterAdapter(java.util.function.Consumer))
[mouseExitAdapter](http://help.eclipse.org/2021-03/topic/org.eclipse.platform.doc.isv/reference/api/org/eclipse/swt/events/MouseTrackListener.html#mouseExitAdapter(java.util.function.Consumer))
[focusLostAdapter](http://help.eclipse.org/2021-03/topic/org.eclipse.platform.doc.isv/reference/api/org/eclipse/swt/events/FocusListener.html#focusLostAdapter(java.util.function.Consumer))

I think there are much more....

Unit tests 100% successful:
image

### CODE REVIEW

**Comment by wolfgang-ch** [comment]
> @wolfgang-ch Do you know those too ? I just discovered and played with them 😄
> 
> [mouseEnterAdapter](http://help.eclipse.org/2021-03/topic/org.eclipse.platform.doc.isv/reference/api/org/eclipse/swt/events/MouseTrackListener.html#mouseEnterAdapter(java.util.function.Consumer))
> [mouseExitAdapter](http://help.eclipse.org/2021-03/topic/org.eclipse.platform.doc.isv/reference/api/org/eclipse/swt/events/MouseTrackListener.html#mouseExitAdapter(java.util.function.Consumer))
> [focusLostAdapter](http://help.eclipse.org/2021-03/topic/org.eclipse.platform.doc.isv/reference/api/org/eclipse/swt/events/FocusListener.html#focusLostAdapter(java.util.function.Consumer))
> 
> I think there are much more....

A few days ago, I discovered one of them


mouseExitAdapter

**Comment by wolfgang-ch** [comment]
@FJBDev 
Can you recreate this PR again, I wanted to do it this morning but github was down https://www.githubstatus.com/incidents/76nv9h8pmkv4?utm_ts=1622626143 after doing it now, I've pressed the wrong button :-)

**Comment by FJBDev** [comment]
> 
> 
> @FJBDev
> Can you recreate this PR again, I wanted to merge it this morning but github was down https://www.githubstatus.com/incidents/76nv9h8pmkv4?utm_ts=1622626143 and after merging it now, I've pressed the wrong button :-) (discarded it in my repo)

@wolfgang-ch I have recreated my PR [here](https://github.com/wolfgang-ch/mytourbook/pull/352).

**Comment by wolfgang-ch** [comment]
> 
> 
> > @wolfgang-ch Do you know those too ? I just discovered and played with them 😄
> > [mouseEnterAdapter](http://help.eclipse.org/2021-03/topic/org.eclipse.platform.doc.isv/reference/api/org/eclipse/swt/events/MouseTrackListener.html#mouseEnterAdapter(java.util.function.Consumer))
> > [mouseExitAdapter](http://help.eclipse.org/2021-03/topic/org.eclipse.platform.doc.isv/reference/api/org/eclipse/swt/events/MouseTrackListener.html#mouseExitAdapter(java.util.function.Consumer))
> > [focusLostAdapter](http://help.eclipse.org/2021-03/topic/org.eclipse.platform.doc.isv/reference/api/org/eclipse/swt/events/FocusListener.html#focusLostAdapter(java.util.function.Consumer))
> > I think there are much more....
> 
> A few days ago, I discovered one of them
> 
> mouseExitAdapter

You can further reduce the code with a static import, which I also do, when I don't forget it

image

**Comment by FJBDev** [comment]
> You can further reduce the code with a static import, which I also do, when I don't forget it
> 
> image

Even better! I will do that in the future.

**Pull request merged**
