### PR TITLE
Updating the GeoCompareView values when the measurement system has changed

### PR DESCRIPTION
**Pull request by FJBDev**
Issue initially reported [here](https://sourceforge.net/p/mytourbook/discussion/622811/thread/c8861e9400/#9cd2)

### CODE REVIEW

**Comment by wolfgang-ch** [comment]
@FJBDev 
Since I do a squash and merge or PR's, these PR's in the Github view contains all commits since I'm using also squash with the merge command. The merge comment contains also all commit comments which I now started to keep only the last once.

The good thing is that the Eclipse compare of your PR with the main branch do show only the modified files.

Is it possible that you are doing the squash?
To keep you original commit comments it may be possible that you squash a separate branch but I've not that much experience with squashing.

**Comment by wolfgang-ch** [comment]
When I try to merge this PR into main, I get many merge conflicts in 4 files, also deleted files are recreated

I've not received a notification mail the last few PR's. I just discovered this PR this morning.


mt-merge-conflict-2


mt-merge-conflict

**Comment by FJBDev** [comment]
> 
> 
> When I try to merge this PR into main, I get many merge conflicts in 4 files, also deleted files are recreated
> 
> I've not received a notification mail the last few PR's. I just discovered this PR this morning.
> 
> mt-merge-conflict-2
> 

I don't see any conflicts and when I try to compare your main branch with my main branch, I see that everything looks good
image

But I think it's because you didn't "update" your FJBDev branch with main. I've noticed that in the past days, you were only merging my main branch but you also need to update your FJBDev branch. That is something that remains a mistery to me with Git.

image

**Comment by FJBDev** [comment]
>  b



> 
> 
> @FJBDev
> Since I do a squash and merge or PR's, these PR's in the Github view contains all commits since I'm using also squash with the merge command. The merge comment contains also all commit comments which I now started to keep only the last once.
> 
> The good thing is that the Eclipse compare of your PR with the main branch do show only the modified files.
> 
> Is it possible that you are doing the squash?
> To keep you original commit comments it may be possible that you squash a separate branch but I've not that much experience with squashing.

I can do the squash if you want. But there will still be cases where you might have to squash yourself.
Example: Let's say I do a PR and I squash. You review it and ask me to fix something. Then I do another commit and I can't "squash" the new one with the previous one and now you have 2 commits.

**Comment by FJBDev** [comment]
@wolfgang-ch 
See, your FJBDev branch is "71" commits behind your master.
Maybe when you merge main into FJBDev, it should resolve your conflicts.

image

**Comment by wolfgang-ch** [comment]
This is the way I did and which created the above conflicts https://github.com/wolfgang-ch/mytourbook/pull/263#issuecomment-747566110


- First I checkout my main
- Select you FJBDev
- Run Eclipse merge

mt-merge


After the merge, this dialog is displayed and the stating view contains what you see above https://github.com/wolfgang-ch/mytourbook/pull/263#issuecomment-747566110



mt-merge-result

**Comment by FJBDev** [comment]
@wolfgang-ch Like I mentioned above, you are see conflicts, because your **FJBDev** branch is **71** commits behind your master.

You have 2 solutions:
- Either your resolve the conflicts but it's tedious and takes times.
- You can "cherry-pick" my squashed commit from **FJBDev** to main (but you still will have to "fix" your **FJBDev** branch)
- You discard your FJBDev branch and create a new one from your current main. Then I can resubmit my PR.

In the future, you need to make sure you merge your **FJBDev** branch with main so that it doesn't end up being "behind" and then have conflicts.

**Comment by FJBDev** [comment]
I will let you choose what the best way going forward is but I have to admit that It was weird for me to see 131 files changed in my last several pull requests when I only modified a few files. And that was because the FJBDev branch was not up-to-date

image

**Comment by wolfgang-ch** [comment]
> You have several solutions:
> 
>     * Either your resolve the conflicts but it's tedious and takes times.
> 
>     * You can "cherry-pick" my squashed commit from **FJBDev** to main (but you still will have to "fix" your **FJBDev** branch so that it doesn't happen again)
> 
>     * You discard your FJBDev branch and create a new one from your current main. Then I can resubmit my PR.
> 

When I cherry pick the 8aa7e22 commit from your repo, it creates the same conflicts

mt-git-with-fjbdev


I crated a new FJBDev branch

mt-new-fjbdev


>In the future, you need to make sure you merge your FJBDev branch with main so that it doesn't end up being "behind" and then have conflicts.
>Or you can give me permission to your FJBDev branch so I can make sure it's merged and up-to-date and then I create a Pull Request to your main. But I understand that you prefer to keep permissions

I could give you write access to the FJBDev branch but I'm lost how to configure it in the branch settings

mt-branch-access

**Comment by FJBDev** [comment]
Yes, that seems like the good window as I can read ion this [doc](https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/enabling-branch-restrictions)

I actually received an email invitation but when I click on it, I get this error :
image

**Comment by wolfgang-ch** [comment]
> I actually received an email invitation but when I click on it, I get this error :
> image

First I wanted to see when I give you access if I can set it more precisely but then immediately it has send you the invitation mail which I have removed afterwards which is now creating the error.

I've not yet read tons of github documentations if I can give you write access for a branche.

**Comment by wolfgang-ch** [comment]
> In the future, you need to make sure you merge your **FJBDev** branch with main so that it doesn't end up being "behind" and then have conflicts.

I've pinned this text on my desktop

fjbdev-merge

**Comment by FJBDev** [comment]
> 
> 
> > In the future, you need to make sure you merge your **FJBDev** branch with main so that it doesn't end up being "behind" and then have conflicts.
> 
> I've pinned this text on my desktop
> 

That will work. Though if you find how to give me write permission to the FJBDev branch, I will make sure it is up-to-date every time I do a new PR.

**Comment by FJBDev** [comment]
> 
> I've not yet read tons of github documentations if I can give you write access for a branche.

I don't know exactly how to give permission.
In the [other project](https://github.com/patrovite/Course_Generator) that I contribute to, the owner gave me permissions and managing my own branch has worked pretty well since I contribute in 2017

**Pull request merged**
