### PR TITLE
Map25 Adding Tooltips for Slideout. Stepsize for spinner was to fine

### PR DESCRIPTION
**Pull request by telemaxx**
it was not clear to me where the number next to the color was used for. so i added a Tooltip for the opacity.

in the tourtrack slideout two spinner where set to:
`_spinnerOutline_Width.setDigits(1);`
due that `spinnerOutline_Width.setIncrement(1); `  results in a stepsize of 0.1
so if i want to change the spinner value by 2 i have to press the plus key 20 times...
so i set the stepsize to 5.

grafik

### CODE REVIEW

**Comment by wolfgang-ch** [comment]
> 
> 
> it was not clear to me where the number next to the color was used for. so i added a Tooltip for the opacity.
> 
> in the tourtrack slideout two spinner where set to:
> `_spinnerOutline_Width.setDigits(1);`
> due that `spinnerOutline_Width.setIncrement(1); ` results in a stepsize of 0.1
> so if i want to change the spinner value by 2 i have to press the plus key 20 times...
> so i set the stepsize to 5.
> 

For all spinner controls, a page up/down is mostly set to 10 which needs less key strokes and also in MT all spinner controls have mouse accelerated buttons, press `<Ctrl>` , `<Shift>`  or `<Ctrl>+<Shift>` when using the mouse wheel

**Comment by telemaxx** [comment]
mouse wheel , I will test. 
I think many users are mousejunkies like me and don't use the accelerators :-)
I have tied different stepsizes.
smaller steps as 0.5 are not visible for track width. I had expected only 1px step would be visible.

**Comment by telemaxx** [comment]
The Textfields of the active Spinners are hard to read.
Compare "Hillshanding" with "photosize"
grafik

Only with the great new dark them.
started from eclipse on linux.

**Comment by wolfgang-ch** [comment]
> grafik
> 
> Only with the great new dark them.
> started from eclipse on linux.

With Ubuntu is looks OK

image

**Comment by telemaxx** [comment]
ah okay. Problem of my very special configuration.

**Pull request merged**
