### PR TITLE
Dropbox Integration - Fixes per suggestions - Part 3

### PR DESCRIPTION
**Pull request by FJBDev**
-  The name Dropbox or any other external file system name in the import actions list and the device folder fields is surrounded with curly braces

image

- Fix for possible NPE

- The device folder is cleaned up when the device type is changed.

- Bugfix easy Import: When importing files, the tour type is set only if it is checked in the launcher configuration

@wolfgang-ch I recommend to test with a fresh `.metadata` folder when I do modifications like this one to `DialogEasyImportConfig.java `

### CODE REVIEW

**Comment by wolfgang-ch** [comment]
I get this exception when 

* Select existing import action
* Select Dropbox in 2.
* Press Browse... button for the folder in 2.

At this moment I've not yet setup the Dropbox authentication.

`java.lang.NullPointerException
	at net.tourbook.common.FileSystemManager.lambda$2(FileSystemManager.java:154)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:174)
	at java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1359)
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:498)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.findAny(ReferencePipeline.java:469)
	at net.tourbook.common.FileSystemManager.getTourbookFileSystem(FileSystemManager.java:155)
	at net.tourbook.importdata.DialogEasyImportConfig.onSelect_IC_Folder_Device(DialogEasyImportConfig.java:4050)
	at net.tourbook.importdata.DialogEasyImportConfig.access$28(DialogEasyImportConfig.java:4042)
	at net.tourbook.importdata.DialogEasyImportConfig$14.widgetSelected(DialogEasyImportConfig.java:1387)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:252)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4105)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1037)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:3922)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3524)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:823)
	at org.eclipse.jface.window.Window.open(Window.java:799)
	at net.tourbook.ui.views.rawData.RawDataView.action_Easy_SetupImport(RawDataView.java:695)
	at net.tourbook.ui.views.rawData.RawDataView.onBrowser_LocationChanging_Runnable(RawDataView.java:4227)
	at net.tourbook.ui.views.rawData.RawDataView.access$37(RawDataView.java:4215)
	at net.tourbook.ui.views.rawData.RawDataView$42.run(RawDataView.java:4201)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:185)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:3897)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3527)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1160)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1049)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
`

dropbox-exception

**Comment by wolfgang-ch** [comment]
I get this error when

* Create a new import action
* Select Dropbox in 2.
* Press Browse... button for the folder in 2.

At this moment I've not yet setup the Dropbox authentication.

-> when dropbox is selected in 2. then the browse button should be disabled when not yet authenticated with dropbox

dropbox-error

**Comment by wolfgang-ch** [comment]
When I'm authenticated but have not yet selected a folder, then Dropbox is not displayed with curly braces.

dropbox-authenticated

**Comment by wolfgang-ch** [comment]
I forgot to pull the merged PR, so forget https://github.com/wolfgang-ch/mytourbook/pull/193#issuecomment-642680549 this do not occure,

this issue https://github.com/wolfgang-ch/mytourbook/pull/193#issuecomment-642684497 is still available

and curly braces are also displayed in https://github.com/wolfgang-ch/mytourbook/pull/193#issuecomment-642690217

I shouldn't have tried to review your PR at this time because my brain was already tired, sorry for that.

**Comment by FJBDev** [comment]
> 
> 
> When I'm authenticated but have not yet selected a folder, then Dropbox is not displayed with curly braces.
> 
> dropbox-authenticated

I can't reproduce and it works as expected (i.e. : the curly braces appear)
Are you sure you tested after merging my PR ?

image

**Comment by FJBDev** [comment]
> 
> 
> I forgot to pull the merged PR, so forget [#193 (comment)](https://github.com/wolfgang-ch/mytourbook/pull/193#issuecomment-642680549) this do not occure,
> 
> this issue [#193 (comment)](https://github.com/wolfgang-ch/mytourbook/pull/193#issuecomment-642684497) is still available
> 
> and curly braces are also displayed in [#193 (comment)](https://github.com/wolfgang-ch/mytourbook/pull/193#issuecomment-642690217)
> 
> I shouldn't have tried to review your PR at this time because my brain was already tired, sorry for that.

No worries, I have fixed that in my new PR.

**Comment by FJBDev** [comment]
> 
> 
> When I'm authenticated but have not yet selected a folder, then Dropbox is not displayed with curly braces.
> 
> dropbox-authenticated

Fixed

**Pull request merged**
