### PR TITLE
Map25: adding preference page for photolayer

### PR DESCRIPTION
**Pull request by telemaxx**
new preferencepage "Apperance" bellow map25 like in map2D
grafik

changing colors:
mapbookmark are blue like in toolbar(old: yellow)
photorating stars now yellow(old: black)

### CODE REVIEW

**Comment by telemaxx** [comment]
grafik

**Comment by wolfgang-ch** [comment]
> new preferencepage "Apperance" bellow map25 like in map2D
> grafik


Why are you not using the `2.5D Map Options` slideout or a new slideout to configure new features?
"Put the features closer to where it is used." this is the motto which I try to follow since a few years.


This was my tour on Wednesday :-)

**Comment by telemaxx** [comment]
> Why are you not using the 2.5D Map Options slideout or a new slideout to configure new features?

yes, you're right, that is better.
and it seems to be easier to implement. i close this PR.

**Comment by telemaxx** [comment]
what do you think of changing the colors?
map bookmarks in blue like in toolbar

83872229-da8aff80-a731-11ea-9cc9-93aeb2c6c8a3

**Comment by wolfgang-ch** [comment]
A bookmark color should be customizable, it makes sense that the default color is blue like in the toolbar

**Comment by telemaxx** [comment]
Button in GUI is implemented. But without any function yet.
grafik

now i will try to implement the functions of my "preference appearance page" branch.
maybe i can use "cherry picking" for that. i never used that...

**Pull request closed without merging**
