### PR TITLE
Added the ability to create unlimited dropbox easy import configurations

### PR DESCRIPTION
**Pull request by FJBDev**
- Now the Dropbox folder selection is made for each Easy Import Config so that the user can watch several different folders (instead of in a single preference location)

image

</br>

- DeviceType is filled dynamically (i.e. if the plugin is not activated, then the device will not appear in the device drop down menu)

- Code improvements

### CODE REVIEW

**Comment by wolfgang-ch** [comment]
I got this exception when using my old dropbox easy import profile, however the dropbox plugin was not yet enabled:

`java.lang.NullPointerException
	at net.tourbook.importdata.DialogEasyImportConfig.restoreState(DialogEasyImportConfig.java:4283)
	at net.tourbook.importdata.DialogEasyImportConfig.create(DialogEasyImportConfig.java:719)
	at org.eclipse.jface.window.Window.open(Window.java:788)
	at net.tourbook.ui.views.rawData.RawDataView.action_Easy_SetupImport(RawDataView.java:695)
	at net.tourbook.ui.views.rawData.RawDataView.onBrowser_LocationChanging_Runnable(RawDataView.java:4227)
	at net.tourbook.ui.views.rawData.RawDataView.access$37(RawDataView.java:4215)
	at net.tourbook.ui.views.rawData.RawDataView$42.run(RawDataView.java:4201)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:185)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:3897)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3527)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1160)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1049)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:658)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:557)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:154)
	at net.tourbook.application.Application.start(Application.java:36)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:657)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:594)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1447)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1420)
`

**Comment by wolfgang-ch** [comment]
The name `Dropbox` in the import actions list and the device folder fields should be displayed not as a "folder" name, maybe it should be surrounded with brackets or other characters to distinguish between local and clould device names.

dropbox-prefix

**Comment by wolfgang-ch** [comment]
When a local folder is selected in the import actions list, then Dropbox can be selected in 2.
-> the local device folder is still displayed

Maybe the device folder should be cleanedup when local/cloud dropbox is changed.

dropbox-with-local-folder

**Comment by wolfgang-ch** [comment]
I just discovered this exception (it's 2 times in my console) but cannot tell when it occured

`java.lang.NullPointerException
	at net.tourbook.common.FileSystemManager.lambda$2(FileSystemManager.java:154)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:174)
	at java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1359)
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:498)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.findAny(ReferencePipeline.java:469)
	at net.tourbook.common.FileSystemManager.getTourbookFileSystem(FileSystemManager.java:155)
	at net.tourbook.importdata.DialogEasyImportConfig.onSelect_IC_Folder_Device(DialogEasyImportConfig.java:4050)
	at net.tourbook.importdata.DialogEasyImportConfig.access$28(DialogEasyImportConfig.java:4042)
	at net.tourbook.importdata.DialogEasyImportConfig$14.widgetSelected(DialogEasyImportConfig.java:1387)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:252)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4105)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1037)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:3922)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3524)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:823)
	at org.eclipse.jface.window.Window.open(Window.java:799)
	at net.tourbook.ui.views.rawData.RawDataView.action_Easy_SetupImport(RawDataView.java:695)
	at net.tourbook.ui.views.rawData.RawDataView.onBrowser_LocationChanging_Runnable(RawDataView.java:4227)
	at net.tourbook.ui.views.rawData.RawDataView.access$37(RawDataView.java:4215)
	at net.tourbook.ui.views.rawData.RawDataView$42.run(RawDataView.java:4201)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:185)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:3897)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3527)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1160)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1049)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:658)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:557)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:154)
	at net.tourbook.application.Application.start(Application.java:36)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:657)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:594)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1447)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1420)
`

**Comment by FJBDev** [comment]
> DialogEasyImportConfig



> 
> 
> I just discovered this exception (it's 2 times in my console) but cannot tell when it occured
> 
> `java.lang.NullPointerException at net.tourbook.common.FileSystemManager.lambda$2(FileSystemManager.java:154) at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:174) at java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1359) at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126) at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:498) at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485) at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152) at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) at java.util.stream.ReferencePipeline.findAny(ReferencePipeline.java:469) at net.tourbook.common.FileSystemManager.getTourbookFileSystem(FileSystemManager.java:155) at net.tourbook.importdata.DialogEasyImportConfig.onSelect_IC_Folder_Device(DialogEasyImportConfig.java:4050) at net.tourbook.importdata.DialogEasyImportConfig.access$28(DialogEasyImportConfig.java:4042) at net.tourbook.importdata.DialogEasyImportConfig$14.widgetSelected(DialogEasyImportConfig.java:1387) at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:252) at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89) at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4105) at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1037) at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:3922) at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3524) at org.eclipse.jface.window.Window.runEventLoop(Window.java:823) at org.eclipse.jface.window.Window.open(Window.java:799) at net.tourbook.ui.views.rawData.RawDataView.action_Easy_SetupImport(RawDataView.java:695) at net.tourbook.ui.views.rawData.RawDataView.onBrowser_LocationChanging_Runnable(RawDataView.java:4227) at net.tourbook.ui.views.rawData.RawDataView.access$37(RawDataView.java:4215) at net.tourbook.ui.views.rawData.RawDataView$42.run(RawDataView.java:4201) at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40) at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:185) at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:3897) at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3527) at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1160) at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338) at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1049) at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155) at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:658) at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338) at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:557) at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:154) at net.tourbook.application.Application.start(Application.java:36) at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203) at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137) at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107) at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401) at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255) at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.lang.reflect.Method.invoke(Method.java:498) at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:657) at org.eclipse.equinox.launcher.Main.basicRun(Main.java:594) at org.eclipse.equinox.launcher.Main.run(Main.java:1447) at org.eclipse.equinox.launcher.Main.main(Main.java:1420) `

I think it's because you had an old serialized Import Config with the new code so it did an exception.
I should have recommended to start with a new and fresh metadata folder.

**Comment by FJBDev** [comment]
> 
> 
> I got this exception when using my old dropbox easy import profile, however the dropbox plugin was not yet enabled:
> 
> `java.lang.NullPointerException at net.tourbook.importdata.DialogEasyImportConfig.restoreState(DialogEasyImportConfig.java:4283) at net.tourbook.importdata.DialogEasyImportConfig.create(DialogEasyImportConfig.java:719) at org.eclipse.jface.window.Window.open(Window.java:788) at net.tourbook.ui.views.rawData.RawDataView.action_Easy_SetupImport(RawDataView.java:695) at net.tourbook.ui.views.rawData.RawDataView.onBrowser_LocationChanging_Runnable(RawDataView.java:4227) at net.tourbook.ui.views.rawData.RawDataView.access$37(RawDataView.java:4215) at net.tourbook.ui.views.rawData.RawDataView$42.run(RawDataView.java:4201) at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40) at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:185) at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:3897) at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3527) at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1160) at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338) at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1049) at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155) at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:658) at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338) at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:557) at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:154) at net.tourbook.application.Application.start(Application.java:36) at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203) at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137) at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107) at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401) at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255) at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.lang.reflect.Method.invoke(Method.java:498) at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:657) at org.eclipse.equinox.launcher.Main.basicRun(Main.java:594) at org.eclipse.equinox.launcher.Main.run(Main.java:1447) at org.eclipse.equinox.launcher.Main.main(Main.java:1420) `


I think it's because you had an old serialized Import Config with the new code so it did an exception.
I should have recommended to start with a new and fresh metadata folder.
It should not happen for the user but I will keep an eye on that

**Comment by FJBDev** [comment]
> 
> 
> When a local folder is selected in the import actions list, then Dropbox can be selected in 2.
> -> the local device folder is still displayed
> 
> Maybe the device folder should be cleanedup when local/cloud is changed.
> 
> dropbox-with-local-folder

Fixed in my upcoming PR

**Comment by FJBDev** [comment]
> 
> 
> The name `Dropbox` in the import actions list and the device folder fields should be displayed not as a "folder" name, maybe it should be surrounded with brackets or other characters to distinguish between local and clould device names.
> 
> dropbox-prefix

I like the bracket idea so it would be like this `[Dropbox]/Folder/file.extension`

**Comment by wolfgang-ch** [comment]
A clould is not angular, so I would prefer parenthesis to distinguish them in the import action list

`(Dropbox)/Folder/file.extension`

**Comment by wolfgang-ch** [comment]
Curly braches (is more cloudy) is an alternative, came in my mind after my daily midday sleep

`{Dropbox}/Folder/file.extension`

**Pull request merged**
