### PR TITLE
Map25 experimental: show photo title on/off - reducing noise for wolfgang ;-)

### PR DESCRIPTION
**Pull request by telemaxx**
this time without merging main before, otherwise to many files are changed.
after undoing that merge every project becomes red inside eclipse.
so i had to remove all projects and reimportint them again.

### CODE REVIEW

**Comment by telemaxx** [comment]
still 321 files changed, because the maps25-experimental was not merged for a very long period. 9 month?
in this time 20.2 and 20.3 was released.
dont know how to handle.

**Comment by wolfgang-ch** [comment]
You have not yet merged `main` into your `experimental` branch, only into your `master` (which is now `main`) and `map25`
 
mt-merge

**Comment by telemaxx** [comment]
that is because i have reverted the merging via hard reset.
with merging it was https://github.com/wolfgang-ch/mytourbook/pull/182
"result was 638 files changed"
that PR i had closed


before my reset, i created a new branch as backup.
history looked like (blue line is my branch):
grafik

**Comment by wolfgang-ch** [comment]
The github merge tool is not very helpful (useless) to see the differences. I'm using the Eclipse branch compare tool to veryfy your branches before they are merged into `main`

Select both commits which you want to compare and compare it with _Compare with Each Other in Tree_

mt-merge

**Comment by telemaxx** [comment]
frustrating
when i switch between 2 branches map25experimental on 20.3 and  experimental on 20.8
many projects becomes red and it seem so that nattable and collections are also gone after switching.

the version based on 20.3 i got working after removing and reimporting in eclipse ws.

for now i giving up.

**Pull request closed without merging**
