### PR TITLE
Readme Update

### PR DESCRIPTION
**Pull request by telemaxx**
and a test if  github is working again.

Was a pain yersterday to find the problem why pushing was not working anymore.
took me 1-2h. solution was https://github.com/settings/tokens
after i solved this, local git was not in sync with the remote.
So i deleted the local git an started from scratch in eclipse...

### CODE REVIEW

**Comment by FJBDev** [comment]
> Was a pain yersterday to find the problem why pushing was not working anymore.
> took me 1-2h. solution was https://github.com/settings/tokens
> after i solved this, local git was not in sync with the remote.
> So i deleted the local git an started from scratch in eclipse...

Are you talking about this `push `issue ?
image

**Comment by telemaxx** [comment]
yes, "not permitted"
in the last weeks I got several email from github telling me I should do something. I have ignored them. 
then push was not possible anymore. 

I had to create a token see my link. 
after that had to use this as user/password.

**Comment by telemaxx** [comment]
https://www.jasong-designs.com/2021/06/29/how-to-push-to-github-with-an-authentication-token/

**Comment by FJBDev** [comment]
That's what I did too this morning and now I can push again.

**Comment by wolfgang-ch** [comment]
I did not had such an access issue within the last days, but time will tell

**Comment by wolfgang-ch** [comment]
@telemaxx 
A day ago I saw this PR and it was in draft mode, then I saw a button similar like "ready for review", pressed it and this PR turned from draft into normal mode. I pressed such a button the first time, so I didn't know what would happen :-)
I don't have a button to revert it back, do you wan't that I merge this PR?

**Comment by telemaxx** [comment]
@wolfgang-ch 
yes you can merge it. primary it was a   test if everything with github is working again and I want to try this "draft mode"

**Pull request merged**
