### PR TITLE
Tour Charted Inverted pace without code improvements

### PR DESCRIPTION
**Pull request by FJBDev**
This PR reverts ALL my code improvements in this previous [PR](https://github.com/wolfgang-ch/mytourbook/pull/306)

If you compare with main, you will only see the useful code to address the pace chart issue.

### CODE REVIEW

**Review by wolfgang-ch — COMMENTED** [review]
Now reviewing this PR took me 5 minutes.

There are 2 things which should be improved:

* The horizontal sliders are swapped when dragged, which I already mentioned in a comment but there were not yet any complain, now it's easier to discover

mt pace horizontal slider

* The user should have an option to select the direction where high/low values are displayed because this is a big change and maybe not all users like it. You can place the UI below the heartbeat and group them into a new group "Graphs"

mt pace in chart options

**Comment by wolfgang-ch** [comment]
I just discovered that the slider value and scale value are not the same


mt pace value vs scale 2

**Comment by FJBDev** [comment]
>     * The horizontal sliders are swapped when dragged, which I already mentioned in a comment but there were not yet any complain, now it's easier to discover

I will investigate this
> 
>     * The user should have an option to select the direction where high/low values are displayed because this is a big change and maybe not all users like it. You can place the UI below the heartbeat and group them into a new group "Graphs"
> 
 Which one would you prefer by default ?

**Comment by FJBDev** [comment]
> I just discovered that the slider value and scale value are not the same


Good catch, I will investigate this

**Comment by wolfgang-ch** [comment]
> > * The user should have an option to select the direction where high/low values are displayed because this is a big change and maybe not all users like it. You can place the UI below the heartbeat and group them into a new group "Graphs"
> >
> 
> Which one would you prefer by default ?

What is more common?

We can use the more common as default and have to write into the readme `Changes` section when it's changed

**Comment by FJBDev** [comment]
> What is more common?

I would tend to think that displaying the pace like the speed is more common but nobody has complained all this time.
Other software like Strava do that and now that I know of this bug I wouldn't use the previous display any more but I don't know for the long time users.

**Comment by FJBDev** [comment]
> I just discovered that the slider value and scale value are not the same
> 
I have fixed this issue. 

image

**Comment by FJBDev** [comment]
>     * The horizontal sliders are swapped when dragged, which I already mentioned in a comment but there were not yet any complain, now it's easier to discover
> 
I have fixed this issue as well:

image
image


When we have decided if we want to offer the option to the user to display the pace chart in inverted and non inverted, which one by default, or if we display in inverted only, I will do a new PR.

Also, I think we should invert those valued, what do you think ?

image

**Comment by wolfgang-ch** [comment]
> Also, I think we should invert those values, what do you think ?

It should depend which top/bottom value the user has selected in the new tour chart options for the pace graph.

I just see in this dialog, that the checkboxes are not vertically aligned in the middle.

**Comment by FJBDev** [comment]
> I just see in this dialog, that the checkboxes are not vertically aligned in the middle.

I can fix that

**Comment by FJBDev** [comment]
Oh actually, I see you already fixed it [here](https://github.com/wolfgang-ch/mytourbook/commit/1d91b49c25c357c388142c132fa0ca7d36986a0c)

**Comment by FJBDev** [comment]
Also, the spinners are not vertically aligned

image

**Comment by wolfgang-ch** [comment]
> 
> 
> Also, the spinners are not vertically aligned
> 
> image

You mean horizontally aligned but this is not possible when each spinner has different min/max values. It looks more ugly when the +/- in the spinner control are not in one line (left aligned).

**Comment by FJBDev** [comment]
What about like this ? Does it look better ?

image
I modified it in my new [PR ](https://github.com/wolfgang-ch/mytourbook/pull/311)but let me know if you don't like it and I'll revert it.

**Comment by wolfgang-ch** [comment]
> Does it look better ?

Fore sure :-)

I thought the width could not be set but you've done it with the layout

I just tested it with different min/max values and the spinner width is adjusted accordingly. Power max is 1'000'000, when you reduce it to 100'000 the width of the slideout is smaller

**Comment by wolfgang-ch** [comment]
> 
> 
> > I just discovered that the slider value and scale value are not the same
> 
> I have fixed this issue.
> 
> image

It works now as it should and also the _Daytime_ statistic :-)

It was not much code changes you did but for me it is relative complex code with all the different variables.

**Comment by FJBDev** [comment]
> It was not much code changes you did but for me it is relative complex code with all the different variables.

Indeed, it was little code modification but it was hard to find and took time to test. Sometimes little code changes can have big impact

**Pull request merged**
