### PR TITLE
When selecting a tour with no GPS data, the previous selected activity

### PR DESCRIPTION
**Pull request by FJBDev**
should not appear. In this case, we display the default position

### CODE REVIEW

**Comment by wolfgang-ch** [comment]
When your code would be merged and I have **not** selected a sync tour or sync slider action, then the map is still moved to the default location. 

Sometimes I disable these sync actions that I can see the selected tours but don't want that the map is moved. 

The method showDefaultMap() should not move the map because it is called in different situations.

A solution for your situation could be that a new map option/action can decide what to do.

**Comment by FJBDev** [comment]
Ok, I will investigate further to find a better solution

**Comment by FJBDev** [comment]
@wolfgang-ch : Here is another solution where we move to the default location ONLY when the **current selected tour has no GPS data.**

**Comment by wolfgang-ch** [comment]
The map must have the ability, whenever a tour (of all kinds) is selected, the map is not relocated.

As in my previous post pointed out, there could be an option in the map options slideout to enable/disable the feature which you have implemented

**Comment by FJBDev** [comment]
Sure, my initial goal was not to move the map but so far I can't find a solution to hide the previous track and stay at the same position. The showDefaultMap() doesn't seem to clear the previous displayed track.

I will continue to investigate more.

**Comment by FJBDev** [comment]
Here is another way of handling the original issue :

**Comment by FJBDev** [comment]
I have just tested and it works well, that solution is great!

**Pull request closed without merging**
