### PR TITLE
New features and unit tests enhancements

### PR DESCRIPTION
**Pull request by FJBDev**
-  Adding the possibility to configure a User Agent for each custom map provider 
 
image

- Added the possibility to export the current map view to an image file (jpg, png or bmp) (Per [feature request](https://github.com/wolfgang-ch/mytourbook/issues/174))

image

image

- Unit tests: Fixed the persistence manager issue and now the FitLog and FitLogEx tests are operational and successful

Unit tests 100% successful

image

See, I added mnemonics 😃

### CODE REVIEW

**Comment by wolfgang-ch** [comment]
> image

The action name is a little bit long and contains words which are not needed in the short name, I would name this action e.g. **Export Map As Image**. When a longer description is needed then it could be displayed as tooltip text

mt-action-tooltiptext-2

An improvement could be to also export it to the clipboard.

I've not yet reviewed the code, in which format is the image saved? You should keep in mind that images can be displayed in the map, so jpg or png 24bit should be used.

**Comment by FJBDev** [comment]
> The action name is a little bit long and contains words which are not needed in the short name, I would name this action e.g. **Export Map As Image**. When a longer description is needed then it could be displayed as tooltip text
> 
Ok, I will shorten the text
 

> I've not yet reviewed the code, in which format is the image saved? You should keep in mind that images can be displayed in the map, so jpg or png 24bit should be used.

The export dialog will give you the choice between JPG, BMP and PNG.

image

**Comment by FJBDev** [comment]
@wolfgang-ch I have updated my PR with your suggestion and I have added the action to export the map view in the clipboard

**Comment by wolfgang-ch** [comment]
>     * Added the possibility to export the current map view to an image file (jpg, png or bmp) (Per [feature request](https://github.com/wolfgang-ch/mytourbook/issues/174))
> 
> 
> image

Can you put the export actions into a submenu action (similar like `Dim Map`), 

`E&xport Map`
-- `As &Image...`
-- `To &Clipboard`

**Comment by FJBDev** [comment]
> Can you put the export actions into a submenu action (similar like `Dim Map`),
> 
> `E&xport Map`
> -- `As &Image...`
> -- `To &Clipboard`

Done. I also updated the PR screenshot.

**Review by wolfgang-ch — COMMENTED** [review]
@FJBDev 

Something strange happened, before I merged this PR here with github, I resetted FJBDev branch in my repo to my main branch because I saw this commit as my last commit in this PR. Then I merged and squashed it here with github, but now I don't see any of your modifications in my FJBDev branch.

So I reseted FJBDev in my repo to your last merge 53b9fe744b81d6073f0b15c87d983b8f32b8bb31

Can you create a new PR ?

There are still some ??? how this github merge works

**Comment by FJBDev** [comment]
@wolfgang-ch 
Weird.... Github can be a pain sometimes. I hope we can resolve those issues soon.

I have created a new PR with the same exact modifications [here](https://github.com/wolfgang-ch/mytourbook/pull/291)

**Pull request merged**
