### PR TITLE
Map25 save actions

### PR DESCRIPTION
**Pull request by telemaxx**
again with conflicts ;-(

### CODE REVIEW

**Comment by telemaxx** [comment]
conflict was only the messages.prop file ;-)

**Comment by telemaxx** [comment]
grafik

**Comment by wolfgang-ch** [comment]
First you revert the file...

mt pr 1

...second you merge it with you old file

mt pr 2

...finally this PR has 0 file changes

mt pr 3

**Comment by telemaxx** [comment]
hmmm, i close this.
i have tried to revert the save actions, on my system all the "org.eclipse.jdt.ui.prefs" file are 6,8kB

i its so, everything is hopefully ok.

**Pull request closed without merging**
