### PR TITLE
Removed the code improvements to ONLY have the modifications for the Strava feature

### PR DESCRIPTION
**Pull request by FJBDev**

### CODE REVIEW

**Comment by wolfgang-ch** [comment]
I just did what you suggested before doing the github merge, merge my main into my FJBDev, which contained only this new commit 2fe4f9fa8806767537e557da3ab0fcc36f992aaa. After that I saw these 2 conficting files, when I wanted to merge this PR, these conflicts must have already existed before

mt-merge-conflict

**Comment by FJBDev** [comment]
GitHub says there is no conflict

image

**Comment by FJBDev** [comment]
I have created a PR directly with main and it shows also NO conflicts with main

image

**Comment by FJBDev** [comment]
This is the only difference that I see for those "conflict files", I have put back "arrayList" instead of "List", it shouldn't conflict since the main code has ArrayList.

image

**Comment by wolfgang-ch** [comment]
The same conflict as the last time.

Before I wanted to merge this PR on github, I update my FJBDev with my main, committed it and the conflict occured again. 

When I change the 2 Export...java files from List -> ArrayList then I also need to change it in `net.tourbook.extension.export.ExportTourExtension` to resolve the List issue.

mt-merge-conflict-3


I couldn't delete FJBDev on github to recreate it as the last time, so I create a new FJBDev2, can you create this PR for FJBDev2 ?

**Comment by FJBDev** [comment]
>can you create this PR for FJBDev2

I have just created a PR against [FJBDev2](https://github.com/wolfgang-ch/mytourbook/pull/273) and as of now it doesn't show any conflicts

image

**Pull request closed without merging**
