### PR TITLE
Map25 map25 2 map25

### PR DESCRIPTION
**Pull request by telemaxx**

### CODE REVIEW

**Comment by telemaxx** [comment]
merging wolfgangs main to telemaxxs main was no problem.

merging from main to map25 gave me 2 conflicts. (messages.properties and messages_de.properties)

so i replaces this 2 files in map25 with the 2 files from main branch.

this PR is only to stay in sync(h) ( ;-) ) with wolfgangs map25.

If not good way, please close this PR.

**Comment by FJBDev** [comment]
> this PR is only to stay in sync(h) ( ;-) ) with wolfgangs map25.

😄

**Comment by wolfgang-ch** [comment]
> 
> 
> merging wolfgangs main to telemaxxs main was no problem.
> 
> merging from main to map25 gave me 2 conflicts. (messages.properties and messages_de.properties)
> 
> so i replaces this 2 files in map25 with the 2 files from main branch.
> 
> this PR is only to stay in sync(h) ( ;-) ) with wolfgangs map25.
> 
> If not good way, please close this PR.

Before I merged your last PR into my main branch, I had to solve also 2 conflicts because your map25 branch was not merged with my last main branch, which is OK because your PR was some days older. 

I don't know why you have now also 2 conflicts.

Before I merge a PR, I'm looking with which commit it is lastly merged from my main and then I reset your PR branch in my repo to this commit.

Frederic is always merging his PR branch with the latest main branch in my repo. With this approach I had no conflicts when merging his PR in my main.

**Comment by wolfgang-ch** [comment]
After I've reset your branch to my main ...

image

... now there are 0 file changes in your PR

image

**Pull request closed without merging**
